-- Run this in Supabase SQL editor
create table if not exists public.user_rights (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public."user"(id) on delete cascade,
  function_key text not null,
  is_allowed boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, function_key)
);

create index if not exists idx_user_rights_user_id on public.user_rights(user_id);

