export const ROLE_ACCESS_RIGHTS = {
  superadmin: [
    "dashboard",
    "payments",
    "history",
    "menu",
    "category",
    "inventory",
    "purchase-order",
    "supplier",
    "purchase-return",
    "supplier-outstanding",
    "report",
    "report-inventory",
    "report-total-sales",
    "report-usage",
    "report-sale-usage",
    "report-add-stock",
    "report-purchase",
    "report-profit-loss",
    "report-supplier-outstanding",
    "report-expired",
    "user-create",
    "user-right",
    "internal-consumption",
    "discount-type",
    "purchase",
    "btn-user-add",
    "btn-user-edit",
    "btn-user-delete",
    "btn-inventory-edit",
    "btn-inventory-delete",
    "btn-inventory-edit-category",
    "btn-category-add",
    "btn-category-edit",
    "btn-category-delete",
    "btn-purchase-add",
    "btn-purchase-edit",
    "btn-purchase-delete",
    "btn-report-export",
    "history-complete",
    "history-cancel",
    "btn-history-edit",
  ],
  admin: [
    "dashboard",
    "history",
    "history-complete",
    "history-cancel",
    "inventory",
    "report",
    "report-inventory",
    "report-total-sales",
    "report-usage",
    "report-add-stock",
    "report-purchase",
    "report-profit-loss",
    "report-supplier-outstanding",
    "report-expired",
    "payments",
    "menu",
    "category",
    "internal-consumption",
    "discount-type",
    "purchase",
    "purchase-order",
    "supplier",
    "purchase-return",
    "supplier-outstanding",
    "btn-inventory-edit-category",
    "btn-report-export",
  ],
  chef: ["dashboard", "history", "report", "menu", "category", "internal-consumption"],
  user: ["dashboard", "payments", "history", "report", "internal-consumption"],
};

export const FUNCTION_OPTIONS = [
  { key: "dashboard", label: "Dashboard", group: "Navigation" },
  { key: "payments", label: "Payments", group: "Navigation" },
  { key: "history", label: "History", group: "Navigation" },
  { key: "menu", label: "Menu", group: "Navigation" },
  { key: "category", label: "Category", group: "Navigation" },
  { key: "inventory", label: "Inventory", group: "Navigation" },
  { key: "purchase", label: "Purchase Group", group: "Navigation" },
  { key: "purchase-order", label: "Purchase Order", group: "Navigation" },
  { key: "supplier", label: "Supplier", group: "Navigation" },
  { key: "purchase-return", label: "Purchase Return", group: "Navigation" },
  { key: "supplier-outstanding", label: "Supplier Outstanding", group: "Navigation" },
  { key: "report", label: "Reports Group", group: "Navigation" },
  { key: "report-inventory", label: "Inventory Report", group: "Navigation" },
  { key: "report-total-sales", label: "Total Sales Report", group: "Navigation" },
  { key: "report-add-stock", label: "Add Stock Report", group: "Navigation" },
  { key: "report-usage", label: "Internal Usage Report", group: "Navigation" },
  { key: "report-sale-usage", label: "Sale Usage Report", group: "Navigation" },
  { key: "report-purchase", label: "Purchase Report", group: "Navigation" },
  { key: "report-profit-loss", label: "Profit & Loss Report", group: "Navigation" },
  { key: "report-supplier-outstanding", label: "Supplier Outstanding Report", group: "Navigation" },
  { key: "report-expired", label: "Expired Report", group: "Navigation" },
  { key: "internal-consumption", label: "Internal Consumption", group: "Navigation" },
  { key: "discount-type", label: "Discount Type", group: "Navigation" },
  { key: "user-create", label: "Create User", group: "Navigation" },
  { key: "user-right", label: "User Right", group: "Navigation" },
  { key: "btn-user-add", label: "Button: Add User", group: "Buttons" },
  { key: "btn-user-edit", label: "Button: Edit User", group: "Buttons" },
  { key: "btn-user-delete", label: "Button: Delete User", group: "Buttons" },
  { key: "btn-inventory-edit", label: "Button: Edit Inventory", group: "Buttons" },
  { key: "btn-inventory-delete", label: "Button: Delete Inventory", group: "Buttons" },
  { key: "btn-inventory-edit-category", label: "Button: Edit Inventory Category", group: "Buttons" },
  { key: "btn-category-add", label: "Button: Add Category", group: "Buttons" },
  { key: "btn-category-edit", label: "Button: Edit Category", group: "Buttons" },
  { key: "btn-category-delete", label: "Button: Delete Category", group: "Buttons" },
  { key: "btn-purchase-add", label: "Button: Add Purchase", group: "Buttons" },
  { key: "btn-purchase-edit", label: "Button: Edit Purchase", group: "Buttons" },
  { key: "btn-purchase-delete", label: "Button: Delete Purchase", group: "Buttons" },
  { key: "btn-history-edit", label: "Button: Edit History", group: "Buttons" },
  { key: "btn-report-export", label: "Button: Export Reports", group: "Buttons" },
  { key: "history-complete", label: "History Complete Button", group: "History" },
  { key: "history-cancel", label: "History Cancel Button", group: "History" },
];

const featureFallback = {
  "purchase-order": ["purchase"],
  supplier: ["purchase"],
  "purchase-return": ["purchase"],
  "supplier-outstanding": ["purchase"],
  "report-inventory": ["report"],
  "report-total-sales": ["report"],
  "report-usage": ["report"],
  "report-add-stock": ["report"],
  "report-purchase": ["report"],
  "report-profit-loss": ["report"],
  "report-supplier-outstanding": ["report"],
  "report-expired": ["report"],
};

export function getResolvedAccess(user) {
  if (!user) return [];
  if (user.role === "superadmin") return ROLE_ACCESS_RIGHTS.superadmin;
  if (Array.isArray(user.permissions) && user.permissions.length > 0) return user.permissions;
  return ROLE_ACCESS_RIGHTS[user.role] || [];
}

export function hasFeature(user, feature) {
  if (user?.role === "superadmin") return true;
  const access = getResolvedAccess(user);
  if (access.includes(feature)) return true;
  const fallback = featureFallback[feature] || [];
  return fallback.some((fb) => access.includes(fb));
}
